import logging
from spaceone.core.connector import BaseConnector

_LOGGER = logging.getLogger(__name__)


class FieldConnector(BaseConnector):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @staticmethod
    def list_data() -> list:
        return [
            {
                "name": "custom field1",
                "field": "field-01",
                "text": {
                    "text1": "Dynamic UI 1",
                    "text2": "Dynamic UI 2",
                    "text3": "Dynamic UI 3",
                },
                "enum": {
                    "enum1": "RUNNING",
                    "enum2": "STOPPED",
                    "enum3": "PAUSED",
                },
                "dict": {"key1": "value1", "key2": "value2"},
                "size": {"size1": 100, "size2": 50},
                "datetime": {
                    "datetime1": "2023-11-11T02:53:59.000000+0000",
                    "datetime2": "2023-11-11T11:53:59.000000+0000",
                    "datetime3": "1620034252",
                },
                "state": {
                    "state1": "ACTIVE",
                    "state2": "INACTIVE",
                    "state3": "PAUSED",
                    "state4": "ACTIVE",
                },
                "badge": {
                    "badge1": "RUNNING",
                    "badge2": "STOPPED",
                    "badge3": "PAUSED",
                    "badge4": "RUNNING",
                    "badge5": "RUNNING",
                    "badge6": "RUNNING",
                },
                "more": {
                    "more1": {"button": "show code", "code": "HELLO\nPYTHON"},
                    "more2": {
                        "button": "show table",
                        "data": [
                            {
                                "name": "CUSTOM FIELD1",
                                "type": "general field",
                                "state": "RUNNING",
                            },
                            {
                                "name": "CUSTOM FIELD2",
                                "type": "custom field",
                                "state": "STOPPED",
                            },
                        ],
                    },
                    "more3": {
                        "button": "show items",
                        "data": [
                            {
                                "key": "CUSTOM FIELD1",
                                "value": "general field",
                                "type": "RUNNING",
                            },
                            {
                                "key": "CUSTOM FIELD2",
                                "value": "custom field",
                                "type": "STOPPED",
                            },
                        ],
                    },
                },
                "color": {
                    "black": "black",
                    "white": "white",
                    "gray": "gray",
                    "gray.100": "gray.100",
                    "gray.200": "gray.200",
                    "gray.300": "gray.300",
                    "gray.400": "gray.400",
                    "gray.500": "gray.500",
                    "gray.600": "gray.600",
                    "gray.700": "gray.700",
                    "gray.800": "gray.800",
                    "gray.900": "gray.900",
                    "red": "red",
                    "red.100": "red.100",
                    "red.200": "red.200",
                    "red.300": "red.300",
                    "red.400": "red.400",
                    "red.500": "red.500",
                    "red.600": "red.600",
                    "red.700": "red.700",
                    "red.800": "red.800",
                    "red.900": "red.900",
                    "coral": "coral",
                    "coral.100": "coral.100",
                    "coral.200": "coral.200",
                    "coral.300": "coral.300",
                    "coral.400": "coral.400",
                    "coral.500": "coral.500",
                    "coral.600": "coral.600",
                    "coral.700": "coral.700",
                    "coral.800": "coral.800",
                    "coral.900": "coral.900",
                    "yellow": "yellow",
                    "yellow.100": "yellow.100",
                    "yellow.200": "yellow.200",
                    "yellow.300": "yellow.300",
                    "yellow.400": "yellow.400",
                    "yellow.500": "yellow.500",
                    "yellow.600": "yellow.600",
                    "yellow.700": "yellow.700",
                    "yellow.800": "yellow.800",
                    "yellow.900": "yellow.900",
                    "green": "green",
                    "green.100": "green.100",
                    "green.200": "green.200",
                    "green.300": "green.300",
                    "green.400": "green.400",
                    "green.500": "green.500",
                    "green.600": "green.600",
                    "green.700": "green.700",
                    "green.800": "green.800",
                    "green.900": "green.900",
                    "blue": "blue",
                    "blue.100": "blue.100",
                    "blue.200": "blue.200",
                    "blue.300": "blue.300",
                    "blue.400": "blue.400",
                    "blue.500": "blue.500",
                    "blue.600": "blue.600",
                    "blue.700": "blue.700",
                    "blue.800": "blue.800",
                    "blue.900": "blue.900",
                    "violet": "violet",
                    "violet.100": "violet.100",
                    "violet.200": "violet.200",
                    "violet.300": "violet.300",
                    "violet.400": "violet.400",
                    "violet.500": "violet.500",
                    "violet.600": "violet.600",
                    "violet.700": "violet.700",
                    "violet.800": "violet.800",
                    "violet.900": "violet.900",
                    "peacock": "peacock",
                    "peacock.100": "peacock.100",
                    "peacock.200": "peacock.200",
                    "peacock.300": "peacock.300",
                    "peacock.400": "peacock.400",
                    "peacock.500": "peacock.500",
                    "peacock.600": "peacock.600",
                    "peacock.700": "peacock.700",
                    "peacock.800": "peacock.800",
                    "peacock.900": "peacock.900",
                    "indigo": "indigo",
                    "indigo.100": "indigo.100",
                    "indigo.200": "indigo.200",
                    "indigo.300": "indigo.300",
                    "indigo.400": "indigo.400",
                    "indigo.500": "indigo.500",
                    "indigo.600": "indigo.600",
                    "indigo.700": "indigo.700",
                    "indigo.800": "indigo.800",
                    "indigo.900": "indigo.900",
                },
            }
        ]
